model_time:lint:python:
  image: python:3.11-slim
  stage: lint
  before_script: cd model_time
  script:
    - pip install black==23.3.0
    - black --check src/

model_time:lint:docker:
  image: hadolint/hadolint:v2.12.0-alpine
  stage: lint
  before_script: cd models/model_time
  script: hadolint Dockerfile --ignore DL3008 --ignore DL3015 --ignore DL3059

model_time:lint:mypy:
  image: python:3.11-slim
  stage: lint
  before_script: cd models/model_time
  script:
    - pip install mypy
    - mypy src/

model_time:test:
  image: python:3.11-slim
  stage: test
  before_script: cd model_time
  script:
    - python3 tests/run_tests.py

model_time:build:docker:
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  stage: build
  variables:
    DOCKER_REGISTRY: registry.cri.epita.fr/mateo.lelong/nlp1
    DOCKER_IMAGE: $DOCKER_REGISTRY/models/model_time
    DOCKER_TAG: $CI_COMMIT_TAG
  script:
    - echo "{\"auths\":{\"$DOCKER_REGISTRY\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR/models/model_time --dockerfile $CI_PROJECT_DIR/models/model_time/Dockerfile --destination $DOCKER_IMAGE:$DOCKER_TAG
  only:
    - tags
  except:
    - main
